### ISSUE TITLE
Best way to contribute

### ISSUE THREAD

**Issue by ChrisBland** [ForceDotComLabs/react.force#5]
Hi - Great to see this project and the other react-native + force libs. This goes for all of them

- What is the best way to help out, submit PRs w features we want? Create issues for any feature then work on a prioritized list? Does SFDC have a roadmap you'd like help with?
- Do we need to sign any contribution license with SFDC to contribute (similar to react w facebook)
- Do you have any code standards or guides we should follow? Any jslint files?
- Anything else we should know?

**Comment by wmathurin** [comment]
The react.force libraries will be moving to https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative soon (with Mobile SDK 5.0 later this year).
- PRs should go against the new repo against the unstable branch.
- You should use issues on the new repo for bugs / enhancement requests. For other discussions, you should also check our g+ community: https://plus.google.com/communities/114225252149514546445.
- There is no contribution license to sign.
- We don't have jslint files at this point, we just provide feedback on the PR when we have stylistic differences.
  Thanks for your interest!
