### ISSUE TITLE
SQLite error (file is encrypted or is not a database) when running on physical Android device

### ISSUE THREAD

**Issue by pedramsaleh** [ForceDotComLabs/react.force#6]
I get a strange error for SQLite when running my project on a physical device (Samsung tablet). I'm not using encryption, just regular SmartStore. The project does not produce the error when running on an emulator. 

![combine_images](https://cloud.githubusercontent.com/assets/12803855/20767598/e5441226-b708-11e6-8d66-85423b57ed0a.jpg)

Any indication on why it would produce this on a physical device?

**Comment by bhariharan** [comment]
@pedramsaleh Could you try a different device, such as a `Nexus` or a `Pixel`. Some vendors fork `Android` and this might cause device specific issues.

**Comment by pedramsaleh** [comment]
Doesn't give that error on my phone (Moto X, which is close to stock Android). So it seems like it's perhaps a compatibility issue between SmartStore and the Samsung tablet then? The model is Galaxy Tab S (SM-T800).

**Comment by bhariharan** [comment]
We don't do anything special that's device specific. We use standard APIs for encryption and decryption. Looks like that specific device has something going on.
